# Generated by Django 6.0 on 2026-07-10 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTableInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('row_count', models.IntegerField(default=0)),
                ('data_size', models.BigIntegerField(default=0)),
                ('index_size', models.BigIntegerField(default=0)),
                ('engine', models.CharField(default='InnoDB', max_length=50)),
                ('collation', models.CharField(default='utf8mb4_unicode_ci', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Database Table Info',
                'verbose_name_plural': 'Database Tables Info',
                'ordering': ['table_name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup')], default='full', max_length=20)),
                ('size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Backup',
                'verbose_name_plural': 'Database Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('execution_time', models.FloatField(default=0)),
                ('rows_affected', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Database Query Log',
                'verbose_name_plural': 'Database Query Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
