# Generated by Django 6.0 on 2026-07-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_usersecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitystats',
            name='secure_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='securitystats',
            name='strong_passwords',
            field=models.IntegerField(default=0),
        ),
    ]
