# Generated by Django 6.0 on 2026-07-08 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Vigilant Admin', max_length=100)),
                ('site_description', models.TextField(blank=True, default='Admin Dashboard for Vigilant')),
                ('admin_email', models.EmailField(default='admin@vigilant.com', max_length=254)),
                ('timezone', models.CharField(default='UTC+3', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(default='24h', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('debug_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'General Settings',
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('desktop_notifications', models.BooleanField(default=False)),
                ('order_alerts', models.BooleanField(default=True)),
                ('stock_alerts', models.BooleanField(default=True)),
                ('customer_alerts', models.BooleanField(default=False)),
                ('system_alerts', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('daily_summary', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('session_timeout', models.IntegerField(default=30)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('password_expiry', models.IntegerField(default=90)),
                ('require_strong_password', models.BooleanField(default=True)),
                ('ip_whitelisting', models.BooleanField(default=False)),
                ('login_notifications', models.BooleanField(default=True)),
                ('allow_multiple_sessions', models.BooleanField(default=False)),
                ('session_control', models.CharField(choices=[('strict', 'Strict - Single session only'), ('moderate', 'Moderate - Limited sessions'), ('loose', 'Loose - Multiple sessions allowed')], default='strict', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
    ]
